### ISSUE TITLE
Notificaties van statuswijzigingen

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-zaken#148]
Statuswijzigingen in VIP moeten een notificatie via e-mail of sms naar de inwoner opleveren.
```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/149
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/152
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/153
```
