### ISSUE TITLE
Taken: Een inwoner een taak laten uitvoeren

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-zaken#164]
Deze bestaat uit:

```[tasklist]
### Tasks
- [ ] Een taak aan kunnen maken via VIP
- [ ] Een notificatie van een taak kunnen sturen
- [ ] Een taak kunnen weergeven bij een zaak in Mijn Nijmegen
- [ ] Een taak kunnen uitvoeren (webform?)
- [ ] Een taak kunnen verwerken in VI
- [ ] Een taak kunnen afsluiten
```
