### ISSUE TITLE
EPIC: Statusinformatie VIP ontsluiten

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/mijn-zaken#27]
Overzicht evenementenvergunningen: https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nijmegen.nl%2Fdiensten%2Fevenementen%2Fschema-vergunningen-activiteiten%2F&data=05%7C01%7Cw.van.den.eeckhout%40nijmegen.nl%7Cd7d5e48e855b4ff940b508dba7c20a82%7Ce0f12b69ac3e4ab19294efe7ab4695c5%7C0%7C0%7C638288224053940872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Dgp2ZfUPYxeVbcv%2FSXvS4yzp%2B8fsgb9ZqreCkTWSr4g%3D&reserved=0

## 1. epic:
Om te voldoen aan een transparante overheid, de Nijmegenaar inzicht te geven in de status van zijn lopende zaken bij de gemeente en meer regie te geven op zijn eigen processen, is het belangrijk dat proactief beschikbaar komt op MijnNijmegen. Dit betekent dat statusinformatie uit VIP getoond gaan worden op MijnNijmegen. De statusinformatie is beschikbaar in [open zaak](https://openzaak.org/using-openzaak) bij Woweb.

MVP1: tonen van statusinformatie voor inwoners (DigiD en Yivi) en ondernemers (eHerkenning en Yivi). De statusinformatie bestaat minimaal uit:
- Overzicht lopende en afgesloten aanvragen/zaken
- Details per zaak: Huidige status, reeds doorlopen statussen en nog opvolgende statussen (stappen). Eventueel resultaat bij afgesloten zaak.

Leverancier is Woweb, Michel Verhoeven ([michel@woweb.nl](mailto:michel@woweb.nl)).
UX design: Vladimir is betrokken, er zijn in Den Haag onderzoeken gedaan.
Business adviseur is Khiêm.

```[tasklist]
## Issues acceptatieomgeving
- [x] ~#444~
- [x] ~#310~
- [x] Bespreken opzet met afdeling
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/102
- [x] https://github.com/GemeenteNijmegen/mijn-zaken/issues/1
- [x] GemeenteNijmegen/mijn-nijmegen#481
- [x] GemeenteNijmegen/mijn-nijmegen#482
- [x] GemeenteNijmegen/mijn-nijmegen#483
- [x] GemeenteNijmegen/mijn-zaken#28
- [x] GemeenteNijmegen/mijn-zaken#29
- [ ] #41
- [ ] GemeenteNijmegen/mijn-zaken#30
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/49
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/50
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/114
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/139
```
```[tasklist]
### Issues productieomgeving
- [x] Groen licht afdeling
- [x] Groen licht Tanja
- [x] afspraak met Michel, Khiem en Joost inplannen om vervolg te bepalen
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/117
- [ ] GemeenteNijmegen/mijn-zaken#31
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/206
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/219
```

```[tasklist]
### Klaarzetten productieomgeving
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/230
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/231
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/232
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/288
```

**Comment by joostvanderborg** [comment]
Bijgepraat met Khiem, voor na de vierdaagse demo met afdeling gepland. Om toegang voor ondernemers/organisaties mogelijk te maken moet er vermoedelijk een open-zaak-update gedaan worden bij Woweb. Moet nog uitgezocht. (Zoeken op organisatie kan niet in de draaiende versie).

**Comment by wvdeeckhout** [comment]
Indien er 1 product gekozen moet worden, dan graag evenement melden of vergunning aanvragen[ ](https://app6.nijmegen.nl/#/form/nijmegen/evenementenmeldenofvergunningaanvragen)

**Comment by wvdeeckhout** [comment]
Statusinformatie VIP is sinds 10-1-2024 beschikbaar op Mijn Nijmegen.
