### ISSUE TITLE
EPIC: Uitbreiden statusinformatie VIP met behandelaars

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/mijn-zaken#406]
Het tonen van de behandelaar bij de zaak in Mijn Nijmegen.
Woweb moet een extra rol "medewerker" koppelen in OpenZaak bij de zaak. 
De behandelaar wijzigt gedurende de looptijd van de zaak, dus dit moet geüpdatet kunnen worden.
Daarnaast is het gewenst om met terugwerkende kracht bij alle lopende zaken de behandelaar te tonen. Hier moet een script voor geschreven worden.
Woweb verwacht hier 12 uur voor nodig te hebben.

We wachten op de planning van Woweb om te kijken wanneer dit ingepland kan worden.
```[tasklist]
### Issues
- [x] [behandelaar VIP MijnNijmegen] toevoegen behandelaar in de koppeling door Woweb, start 4 maart op acceptatie
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/407
- [x] [behandelaar VIP MijnNijmegen] Woweb zet dit naar productieomgeving
- [ ] https://github.com/GemeenteNijmegen/mijn-zaken/issues/410
- [ ] [behandelaar VIP MijnNijmegen] testen door afdeling
```
